{% set version = '0.9.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-cowplot
  version: {{ version|replace("-", "_") }}

source:
  fn: cowplot_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/cowplot_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/cowplot/cowplot_{{ version }}.tar.gz
  sha256: 953fd9d6ff370472b9f5a9ee867a423bea3e26e406d08a2192ec1872a2e60047

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-ggplot2 >=2.1.0
    - r-gtable >=0.1.2
    - r-plyr >=1.8.2
    - r-scales

  run:
    - r-base
    - r-ggplot2 >=2.1.0
    - r-gtable >=0.1.2
    - r-plyr >=1.8.2
    - r-scales

test:
  commands:
    - $R -e "library('cowplot')"  # [not win]
    - "\"%R%\" -e \"library('cowplot')\""  # [win]

about:
  home: https://github.com/wilkelab/cowplot
  license: GPL-2
  summary: Some helpful extensions and modifications to the 'ggplot2' package. In particular,
    this package makes it easy to combine multiple 'ggplot2' plots into one and label
    them with letters, e.g. A, B, C, etc., as is often required for scientific publications.
    The package also provides a streamlined and clean theme that is used in the Wilke
    lab, hence the package name, which stands for Claus O. Wilke's plot package.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - druvus
    - jdblischak
