# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vq+pTVWh8rsg9nGHv3ctYjDs/LkQ1bkXnKYikGJprfX6kq8wRMNwNE1ykjJcgny3UuDszXm7mwPRxD5ZQ2LLyk4Br6rpt2iyUwxSiTt69iM/sTuBJ2lPpjNwJ/75EZpRMuGos4EigIMrYEHL9zsOpLDSSOgAW4dDxOWpwIKkdD+/b+lUlFXMwNh7hDtDZBfE8Ec+4RgNmPf92DPoigeix1TCqBSCN0iwgdiKKVe29t5UDOTlBiCzGEpEHSLhe/x8EcArpSelQGgQNkE60VB0q6TxTWx5abVipFkIH/3RrY/Np0EPE9NWOAPdpQEv2a0Ji68ZKHQjtMJQyUTqnAfOBWO9mWTwgAm/sdbWU1qpp3p1EjD/0q4efRaMy/2tkT43deuAIo9R4FaIXZmdUpiF+WSV2N1ZPWN8q6xtaJl8afog815jbWO/K2OXQuu8dwAYcByaC2pglOx+AwQVuWmWQKm4hBt1ZJedha2leIWTMfBB8GxU9jFNFnvD2Dh5xXBQ4uSI/tkQXl1/xpQRy5KfCCiXOqU4JXcuPAJ3jBJ914dDuMW+z1+Fj9AvQAtfdQ2xY8+28+a+tjrfnB0LzJFT6Ru6hdC/vLfX24KLmEYm0iODGGzP1/gG2UKM7GBksi/DBBPqcT9gNf5ubcFJ2/YtU3F3AmNHFzhGMXObn/MtPBo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
