travis:
  secure:
    BINSTAR_TOKEN: SIXeCJc1zUJWy/pY+oO6u8rExeXeQlB/Ap4KUGdix0CD6yiOqczMANfknI6I+GgiP5L8S5o3Qf9TCZ77gFExnDHfaEw4LvQaP/ffHq8cC0y3biZtbpHkxyQFkBGXkN0fCIroVKItp7J37jS1K1oSiW1KDyWvJJkkRv+tlkSBzVoRuEHFZvzXYTgb3oI5IQgmoNhBQsxJfH+ljIiTynyIqyu0mcpP7vFIStYbqM3DlhpBuGJjfYYFe9FTsTvaXDAfKeGJn6JShzLqNkXPhQ6joutH9KaVn3OO0RWk2AnK5d/xDPHIOWGao2+uJ6EYbkw5YkgcYaC1+BmmnbieAkJ3Wo6x/xf49ZRKM9KiQyjk3c+R8ouXVz55zi6njc7W92CuFfhh/9E9SrVA8B4KA5GQ5d3f0P1yaYmsSisK2Y0XM1wp3NFuDFxGMvStBEUZ8q6PZuPimNn6C01VX8MWH3YlNUjZXw60T/RyZGlu2DC8ZuF5hy2lm1ixVq2d3bILhYH6X2a453GqhkB8Aq8PMI0S8tzqUWdSJPrk97114CA8XClplJcGseqVVAB37kOWv3/QT5/lY48I6y6hHQZNU9ZHd5F2olxn8rI76bscEVoGF2YSh2DioT3kXZOXtkXo8GWluDJT+3GOdQPrugJkOwi4GqprD3rjgq3LEtMuop/Z2zw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
