travis:
  secure:
    BINSTAR_TOKEN: Jma2R6s9/W8miHc4Kg/8OaRkUQyh5H/T49WMW/GxFzV+MYHUd7KTL8srUmtwMUe6LfgRZOC/A4jsSNMHYx6jQjTPnz8xA5aiPqlIc7AbC3hevHOYT1M296efVS0KEvrD1nQHn0xM9dW7fKUY46O3Fow1LRC1mNyefD4yDdG3gmokcgbH71SSEuO8xIPSod3QNWZNqVbZc3+lyzZU7z6d6Qg5u9QeOUurJ3tXz9KIwCXo/tcjx6oKApdHVNUbFrtcu0+N5uQ7h0ryB2Qhg6AEe5A/8rAdDtxWVfkEfGAKHINfkIEdXj3J4w/+Nz92MvbRlM4fzpM/dX0uRNmp3wBZRZoFHyQYEI3YzrEe7FkSutUcoWH4w9cSyeUWU4mV9+7CpByZ4Nt3zi14sCXgMRmaIj3PIeftJSoEyfW1eg+5/XtpYKQ22ssCvYSWLIfAKCiAWhpBDxJ/8gHLH7svByM87H0tu6lLLfP5xcAtTy6QijlwjzZBOlzQsQJApZgTaavtotKWAuEt1MiF+jPDwqWWwePGL0MiTGaR5GjlHlMTJSkOPqapE3iISJ17Dt25LJO5P0Cv552URUebmNiryetj8PrdnqDucvbYb2Y/fkNnmWwEnPKGxQkbJ620dcFGKRRHQBwvvs8n2PabyJR/izzdyWfiXS4lUOS2uyiJt2O/KrI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
