appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: vq+pTVWh8rsg9nGHv3ctYjDs/LkQ1bkXnKYikGJprfX6kq8wRMNwNE1ykjJcgny3UuDszXm7mwPRxD5ZQ2LLyk4Br6rpt2iyUwxSiTt69iM/sTuBJ2lPpjNwJ/75EZpRMuGos4EigIMrYEHL9zsOpLDSSOgAW4dDxOWpwIKkdD+/b+lUlFXMwNh7hDtDZBfE8Ec+4RgNmPf92DPoigeix1TCqBSCN0iwgdiKKVe29t5UDOTlBiCzGEpEHSLhe/x8EcArpSelQGgQNkE60VB0q6TxTWx5abVipFkIH/3RrY/Np0EPE9NWOAPdpQEv2a0Ji68ZKHQjtMJQyUTqnAfOBWO9mWTwgAm/sdbWU1qpp3p1EjD/0q4efRaMy/2tkT43deuAIo9R4FaIXZmdUpiF+WSV2N1ZPWN8q6xtaJl8afog815jbWO/K2OXQuu8dwAYcByaC2pglOx+AwQVuWmWQKm4hBt1ZJedha2leIWTMfBB8GxU9jFNFnvD2Dh5xXBQ4uSI/tkQXl1/xpQRy5KfCCiXOqU4JXcuPAJ3jBJ914dDuMW+z1+Fj9AvQAtfdQ2xY8+28+a+tjrfnB0LzJFT6Ru6hdC/vLfX24KLmEYm0iODGGzP1/gG2UKM7GBksi/DBBPqcT9gNf5ubcFJ2/YtU3F3AmNHFzhGMXObn/MtPBo=
