travis:
  secure:
    BINSTAR_TOKEN: EGIzjsn/ykpDY0CECswHdaiHEuB232SoPODjdFw2KHXB/HUWemKms4A6SOrhr043Jbn/fku6MfnjX3LMCtUdzyahtkbyuHL4LNnT5walYb3qPJzEu649P0Y19zRviGbq/Qe2rbyNSYLDRh+94FERitOnU+M4XT2pd1Igu3Eb6JpTY1pXgK8MdnIbzLpBaP4jEvrxdhgpXKu3gu2NOWZEDVdbBcrg/92tX1jWKTdu0IJXmUDAQNnX1Z1a15OXffqtTGHMcyqxbQT6fhXHwmY53s+MuIm6Ksp8YqlSVy9KXjJUm4UOlmKungAkCpdZrMsHG22igWibaWTiPSYjKtdsKRLOxIxpd+COgtqEPLMYlIq2tsfZRc+STEC4qgX1hmiePMhgGtYsQjSA8C9YjNf+RFOTq1XswEto54w1/7xOKSnChy/rDgKDVasJ0Skz8LSc71yz5KuJzBnM3pwGtbUi1Y+Fo9Yz2/zZ8TFxicQSOJrG9oTZGJHk5HC/8mVmSO3z5nZOzR/+UjDsDyDBAjjnA3ERLXz+NpNfoES2XJOZiL/R5MGFZNDR8dFgtD5ZD50B7+pdMoVsDqNSLR3Y+zsvA3Ej+i3c7bFdL+so7O2+0eUsySQY7xgFHRX9qsbxzs3xDRetlRJzsCMbSj5SBN/85a+iNV4BdcQmz1KXleKduHw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
